#!/bin/sh
# note that the shebang in the first line is necessary even for windows!
echo "pre commit"
# stash any unstaged changes
git stash -q --keep-index

# run the tests with Maven
cd TinyME
mvn clean install -Dstyle.color=always

# store the last exit code in a variable
RESULT=$?

# return to the root directory
cd ..

# unstash the unstashed changes
git stash pop -q

# print a message
echo "building and testing done"
echo "the result is $RESULT (0 is good)"

# return the 'mvn clean install' exit code
exit $RESULT
